#!/bin/sh
# SPDX-License-Identifier: GPL 2.0
#
# Small tool that lists all the PEAK-System CAN/CAN-FD devices found
# by the pcan driver (see also lspcan -h).
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Author: Stephane Grosjean <stephane.grosjean@hms-networks.com>
# Contact: <linux.peak@hms-networks.com>
# Copyright (c) 2001-2021 PEAK-System GmbH <www.peak-system.com>
#
MYSELF=`basename $0`
SYSFSROOT="/sys/class"
DRV="pcan"
DRVROOT=${SYSFSROOT}/$DRV
ECHO_E=echo
#ECHO_E="echo -e"
ECHO=/bin/echo

# -- usage
usage()
{
	$ECHO "\
$MYSELF: list PEAK-System CAN 2.0/CANFD/CANXL devices handled by the PCAN driver

Option:
-a | --all        equivalent to: -i -s
-f | --forever    forever loop on devices (^C to stop)
-h | --help       display this help
-i | --info       information about pcan devices
-s | --stats      statistics about pcan devices
-t | --title      display a title line over columns
-T | --tree       tree version
-v | --version    display PCAN version
"
	exit 0
}

# -- main
devlist=""
fmt="l"
display="q"
forever="n"
title="n"
for arg in "$@"; do
	case "$arg" in

	"--help" | "-h" )
		usage
		;;

	"--tree" | "-T" )
		fmt="t"
		;;

	"--info" | "-i" )
		display="i"
		;;

	"--all" | "-a" )
		display="a"
		;;

	"--forever" | "-f" )
		forever="y"
		;;

	"--stats" | "-s" )
		display="s"
		;;

	"--title" | "-t" )
		title="y"
		;;

	"--version" | "-v" )
		if [ -f "$DRVROOT/version" ]; then
			cat $DRVROOT/version
			exit 0
		fi
		$ECHO "Either PCAN driver is not loaded or is older than v8"
		exit 2
		;;
	* )
		devlist="$devlist $arg"
		;;

	esac
done

if [ ! -d $DRVROOT ]; then
	$ECHO "$MYSELF needs PCAN driver to be loaded"
	exit 1
fi
if [ ! -f $DRVROOT/version ]; then
	$ECHO "$MYSELF can't run over versions of PCAN driver less than 8.x"
	exit 1
fi

[ -z "$devlist" ] && devlist=`ls $DRVROOT`

# forever loop
while :; do

d=0

#if [ "$display" == "a" ]; then
#	pcanver=`cat $DRVROOT/version`
#	$ECHO "pcan version: $pcanver"
#fi

if [ "$title" = "y" ]; then
	case "$display" in

	"i" )	# info
		$ECHO -e "dev name\tport\tirq\tclock\tbus\tbtrs"
		;;

	"s" )	# stats
		$ECHO -e "dev name\tport\tbus\t%bus\trx\t%fifo\ttx\t%fifo\terr"
		;;

	"a" )	# all
		$ECHO -e "dev name\tport\tirq\tclock\tbus\t%bus\trx\ttx\terr\tbtrs"
		;;
	esac
fi

for dev in $devlist; do
	[ ! -d $DRVROOT/$dev ] && continue

	line="$dev\t"
	d=`expr $d + 1`

	# simple "ls" mode
	if [ "$display" = "q" ]; then
		$ECHO -e -n $line
		if [ $d -ge 5 ]; then
			echo
			d=0
		fi
		continue
	fi

	prodname=`cat $DRVROOT/$dev/adapter_name`
	cardidx=`cat $DRVROOT/$dev/adapter_number`
	brdname="[${prodname} ${cardidx}]"

	btr=`cat $DRVROOT/$dev/nom_bitrate`
	if [ $btr -ge 1000000 ]; then
		btr=`expr $btr / 1000000`M
	elif [ $btr -ge 1000 ]; then
		btr=`expr $btr / 1000`k
	fi

	fd_btr=""
	if [ -f $DRVROOT/$dev/fd_bitrate ]; then
		fd_btr=`cat $DRVROOT/$dev/fd_bitrate`
		if [ $fd_btr -ge 1000000 ]; then
			fd_btr=`expr $fd_btr / 1000000`M
		elif [ $fd_btr -ge 1000 ]; then
			fd_btr=`expr $fd_btr / 1000`k
		elif [ $fd_btr -eq 0 ]; then
			fd_btr=""
		fi
	fi
	[ -n "$fd_btr" ] && btr="$btr+$fd_btr"

	xl_btr=""
	if [ -f $DRVROOT/$dev/xl_bitrate ]; then
		xl_btr=`cat $DRVROOT/$dev/xl_bitrate`
		if [ $xl_btr -ge 1000000 ]; then
			xl_btr=`expr $xl_btr / 1000000`M
		elif [ $xl_btr -ge 1000 ]; then
			xl_btr=`expr $xl_btr / 1000`k
		elif [ $xl_btr -eq 0 ]; then
			xl_btr=""
		fi
	fi
	[ -n "$xl_btr" ] && btr="$btr+$xl_btr"

	clk=`cat $DRVROOT/$dev/clock`
	if [ $clk -ge 1000000 ]; then
		clk=`expr $clk / 1000000`MHz
	elif [ $btr -ge 1000 ]; then
		clk=`expr $clk / 1000`kHz
	fi

	bus=`cat $DRVROOT/$dev/bus_state`
	case $bus in

	0 )	# PCANFD_UNKNOWN
		bus="CLOSED"
		;;

	1 )	# PCANFD_ERROR_ACTIVE
		bus="ACTIVE"
		;;

	2 )	# PCANFD_ERROR_WARNING
		bus="WARNING"
		;;

	3 )	# PCANFD_ERROR_PASSIVE
		bus="PASSIVE"
		;;

	4 )	# PCANFD_ERROR_BUSOFF
		bus="BUSOFF"
		;;

	esac

	canidx=`cat $DRVROOT/$dev/ctrlr_number`
	case "$fmt" in

	"t" )	# tree
		[ $canidx -eq 0 ] && $ECHO "${brdname}"
		line=" |_ $line"
		;;
	esac

	rxcnt=`cat $DRVROOT/$dev/read`
	txcnt=`cat $DRVROOT/$dev/write`
	errcnt=`cat $DRVROOT/$dev/errors`

	if [ -f $DRVROOT/$dev/bus_load ]; then
		bload=`cat $DRVROOT/$dev/bus_load`
	else
		bload="-"
	fi

	line="${line}CAN`expr $canidx + 1`"

	case "$display" in

	"i" )	# info
		irq=`cat $DRVROOT/$dev/irq`
		[ $irq -eq 0 ] && irq="-"
		line="$line\t$irq\t$clk\t$bus\t$btr"
		;;

	"s" )	# stats
		if [ -f $DRVROOT/$dev/rx_fifo_ratio ]; then
			rxratio=`cat $DRVROOT/$dev/rx_fifo_ratio`
		else
			rxratio="n/a"
		fi
		txratio=`cat $DRVROOT/$dev/tx_fifo_ratio`
		line="$line\t$bus\t$bload\t$rxcnt\t$rxratio\t$txcnt\t$txratio\t$errcnt"
		;;

	"a" )	# all
		irq=`cat $DRVROOT/$dev/irq`
		[ $irq -eq 0 ] && irq="-"
		line="${line}\t$irq\t$clk\t$bus\t$bload\t$rxcnt\t$txcnt\t$errcnt\t$btr"
		;;
	esac

	$ECHO -e $line
done

[ "$forever" != "y" ] && break
sleep 1
clear
done

echo
