Controller:
  ros__parameters:
    time_step: 0.1

    speed:
      maximum: 2.5

      minimum: 0.3

    gains:
      proportional: 2.5

      integral: 0.0

      differential: 0.3
      #lookAhead: 0.22
      lookAhead: 2.2
      #lookAhead: 0.3

    constants:
      # speed: 17.73
      speed: 2.0
      #lookahead: 0.4
      lookahead: 2.8
      #lookahead: 10.0 ew3a tgrbha_ana hzrtk

    drive: "/ackr"

    state: "/zed/zed_node/odom" #will be changed through phases

    path: "/path"  #will be changed through phases
