/lidar_processor_node:
  ros__parameters:
    # FILTERING PARAMS
    


    #filter viewable bounds
    x: [0.0, 8.0]
    y: [-4.0, 8.0]
    z: [-2.0, 2.0]

    #car dimensions for filtering out points on the car itself
    car_x: [-1.0, 1.0]
    car_y: [-0.5, 0.5]




    #ground and wall removal 

    #ground removal params
    ground_level: 0.1 #10cm
    point_num: 10
    distance_threshold: 0.06
    ransac_n: 4
    num_iterations: 200
    horizontal_plane_gradient: 0.8 

    # Downsampling voxel size
    voxel_size: 0.03

    



    #CLUSTERING PARAMS

    # Clustering Params
    cluster_distance_threshold: 0.2 #20 cm between points
    cluster_min_size: 2
    cluster_max_size: 100