# SPDX-License-Identifier: LGPL-2.1-only
#
# Makefile - Python example Makefile (mainly useful to avoid unknown target
#            errors as well as being able to clean tmp files)
#
# Copyright (C) 2001-2025  PEAK System-Technik GmbH
#
# Contact:     <linux.peak@hms-networks.com>
# Maintainer:  Fabrice Vergnaud <fabrice.vergnaud@hms-networks.com>
# Author:      Stephane Grosjean <stephane.grosjean@hms-networks.com>
#
all:
install:
uninstall:
xeno:
rtai:

clean:
	-rm -rf *.pyc __pycache__
