# planning_node:
#   ros__parameters:
#     planning:
#       topics:
#         frame_id: "Fr1A"

#         pathTopic: "/path"
#         odometryTopic: "/carmaker/Odometry"
#         conesTopic: "/carmaker/ObjectList"

#       sorting:
#         thresholdDirectionalAngle: 45.0 # 45.0 degree
#         thresholdAbsoluteAngle: 60.0 #60.0 degree
#         maxNNeighbors: 5
#         maxDist: 6.0 #6.0
#         maxDistToFirst: 6.0
#         maxLength: 15    # INTMax no. of cones 

#       matching:
#         minTrackWidth: 3.0
#         maxSearchRange: 5.0
#         maxSearchAngle: 50.0
#         matchesShouldBeMonotonic: True

#       path:
#         maximalDistanceForValidPath: 5.0
#         mpcPathLength: 15.0 
#         mpcPredictionHorizon: 40
      
#       slice:
#         radius: 20.0
#         angle_deg: 150.0
#===========================GLOBAL PARAMS=================================        
planning_node:
  ros__parameters:
    use_sim_time: true
    planning:
      topics:
        frame_id: "zed_left_camera_frame"

        pathTopic: "/path"
        odometryTopic: "/carmaker/Odometry"
        conesTopic: "/perception_landmarks"

      sorting:
        thresholdDirectionalAngle: 45.0 # 45.0 degree
        thresholdAbsoluteAngle: 60.0 #60.0 degree
        maxNNeighbors: 5
        maxDist: 6.0 #6.0
        maxDistToFirst: 12.0
        maxLength: 12    # INTMax no. of cones 

      matching:
        minTrackWidth: 3.0
        maxSearchRange: 5.0
        maxSearchAngle: 50.0
        matchesShouldBeMonotonic: False

      path:
        maximalDistanceForValidPath: 8.0
        mpcPathLength: 15.0 
        mpcPredictionHorizon: 40
      
      slice:
        radius: 30.0
        angle_deg: 180.0
