# SPDX-License-Identifier: LGPL-2.1-only
#
# Makefile - Build examples of pcanbasic_java
#
# Copyright (C) 2001-2025  PEAK System-Technik GmbH <www.peak-system.com>
#
# Contact:     <linux.peak@hms-networks.com>
# Maintainer:  Fabrice Vergnaud <fabrice.vergnaud@hms-networks.com>
#


all:

clean:

install:
uninstall:
xeno:
rtai:
